export const initialClients = [
  { id: 'client-riverside', name: 'Riverside Leagues Ltd', contact: 'J. Chen', email: 'admin@riversiderg.com.au', venues: 3, plan: 'PAYG', status: 'Active' },
  { id: 'client-northside', name: 'Northside Community Club', contact: 'S. Patel', email: 'ops@northsideclub.com.au', venues: 2, plan: 'PAYG', status: 'Active' },
  { id: 'client-harbourview', name: 'Harbourview Hospitality Group', contact: 'M. Wallace', email: 'finance@harbourview.com.au', venues: 2, plan: 'PAYG', status: 'Active' },
  { id: 'client-riverside-dining', name: 'Riverside Dining', contact: 'A. Morgan', email: 'accounts@riversidedining.com.au', venues: 1, plan: 'Starter', status: 'Draft' }
];

export const initialVenues = [
  { id: 'venue-riverside-rsl', clientId: 'client-riverside', name: 'Riverside RSL Club', state: 'NSW', status: 'Active', IdentityVerifiedEnabled: true, transactions: 84, volume: 145300, lastActivity: '13 Jul 2026', machines: 12, users: 5, smrs: 2 },
  { id: 'venue-riverside-bowling', clientId: 'client-riverside', name: 'Riverside Bowling Club', state: 'NSW', status: 'Active', IdentityVerifiedEnabled: true, transactions: 31, volume: 48320, lastActivity: '12 Jul 2026', machines: 8, users: 4, smrs: 1 },
  { id: 'venue-riverside-lounge', clientId: 'client-riverside', name: 'Riverside Lounge & Bar', state: 'NSW', status: 'Draft', IdentityVerifiedEnabled: false, transactions: 0, volume: 0, lastActivity: 'Not active', machines: 0, users: 1, smrs: 0 },
  { id: 'venue-northside-leagues', clientId: 'client-northside', name: 'Northside Leagues Club', state: 'QLD', status: 'Active', IdentityVerifiedEnabled: true, transactions: 62, volume: 92450, lastActivity: '30 Jul 2026', machines: 9, users: 6, smrs: 2 },
  { id: 'venue-northside-sports', clientId: 'client-northside', name: 'Northside Sports Club', state: 'QLD', status: 'Inactive', IdentityVerifiedEnabled: false, transactions: 12, volume: 12450, lastActivity: '02 Jun 2026', machines: 7, users: 3, smrs: 0 },
  { id: 'venue-harbourview-hotel', clientId: 'client-harbourview', name: 'Harbourview Hotel', state: 'VIC', status: 'Active', IdentityVerifiedEnabled: true, transactions: 45, volume: 67290, lastActivity: '02 Aug 2026', machines: 6, users: 4, smrs: 1 },
  { id: 'venue-harbourview-bistro', clientId: 'client-harbourview', name: 'Harbourview Bistro', state: 'VIC', status: 'Active', IdentityVerifiedEnabled: true, transactions: 19, volume: 27100, lastActivity: '01 Aug 2026', machines: 4, users: 2, smrs: 0 },
  { id: 'venue-grand-bistro', clientId: 'client-riverside-dining', name: 'Riverside Grand Bistro', state: 'ACT', status: 'Active', IdentityVerifiedEnabled: true, transactions: 8, volume: 3200, lastActivity: '10 Jul 2026', machines: 2, users: 2, smrs: 0 }
];

export const initialUsers = [
  { id: 'usr-1a2b3c', username: 'm.santos', email: 'm.santos@riversidersl.com.au', clientId: 'client-riverside', venueIds: ['venue-riverside-rsl'], role: 'Collector', status: 'Active', lastActive: 'Today, 08:42' },
  { id: 'usr-2b3c4d', username: 'j.chen', email: 'j.chen@riversidersl.com.au', clientId: 'client-riverside', venueIds: ['venue-riverside-rsl', 'venue-riverside-bowling'], role: 'Venue Admin', status: 'Active', lastActive: 'Today, 08:36' },
  { id: 'usr-3c4d5e', username: 'd.walsh', email: 'd.walsh@riversidersl.com.au', clientId: 'client-riverside', venueIds: ['venue-riverside-rsl'], role: 'Approver', status: 'Active', lastActive: 'Yesterday' },
  { id: 'usr-4d5e6f', username: 'k.lee', email: 'k.lee@riversidersl.com.au', clientId: 'client-northside', venueIds: ['venue-northside-leagues'], role: 'Authoriser', status: 'Active', lastActive: '31 Jul 2026' },
  { id: 'usr-5e6f7g', username: 'r.nguyen', email: 'r.nguyen@riversidersl.com.au', clientId: 'client-northside', venueIds: ['venue-northside-leagues', 'venue-northside-sports'], role: 'Venue Admin', status: 'Active', lastActive: '30 Jul 2026' },
  { id: 'usr-6f7g8h', username: 'p.sharma', email: 'p.sharma@harbourview.com.au', clientId: 'client-harbourview', venueIds: ['venue-harbourview-hotel'], role: 'Collector', status: 'Blocked', lastActive: '18 Jul 2026' },
  { id: 'usr-7g8h9i', username: 'venue.admin', email: 'admin@riversidedining.com.au', clientId: 'client-riverside-dining', venueIds: ['venue-grand-bistro'], role: 'Venue Admin', status: 'Pending', lastActive: 'Never' }
];

export const initialMachines = [
  // Riverside RSL Club (12 machines: 8 Active, 4 Archived)
  { id: 'm-1', machineId: 'EGM-001', name: 'Aristocrat Lightning Link 1', serialNumber: 'SN-AR-00112', venue: 'Riverside RSL Club', status: 'active', description: '', createdBy: 'System seed', lastUpdatedBy: 'System seed' },
  { id: 'm-2', machineId: 'EGM-002', name: 'Aristocrat Lightning Link 2', serialNumber: 'SN-AR-00113', venue: 'Riverside RSL Club', status: 'active', description: '', createdBy: 'System seed', lastUpdatedBy: 'System seed' },
  { id: 'm-3', machineId: 'EGM-003', name: 'Aristocrat Lightning Link 3', serialNumber: 'SN-AR-00114', venue: 'Riverside RSL Club', status: 'archived', description: '', createdBy: 'System seed', lastUpdatedBy: 'System seed' },
  { id: 'm-4', machineId: 'EGM-004', name: 'IGT Wheel of Fortune 1', serialNumber: 'SN-IGT-2201', venue: 'Riverside RSL Club', status: 'active', description: '', createdBy: 'System seed', lastUpdatedBy: 'System seed' },
  { id: 'm-5', machineId: 'EGM-005', name: 'IGT Wheel of Fortune 2', serialNumber: 'SN-IGT-2202', venue: 'Riverside RSL Club', status: 'archived', description: '', createdBy: 'System seed', lastUpdatedBy: 'System seed' },
  { id: 'm-6', machineId: 'EGM-006', name: 'Konami Dragon Link 1', serialNumber: 'SN-KON-3301', venue: 'Riverside RSL Club', status: 'active', description: '', createdBy: 'System seed', lastUpdatedBy: 'System seed' },
  { id: 'm-7', machineId: 'EGM-007', name: 'Konami Dragon Link 2', serialNumber: 'SN-KON-3302', venue: 'Riverside RSL Club', status: 'active', description: '', createdBy: 'System seed', lastUpdatedBy: 'System seed' },
  { id: 'm-8', machineId: 'EGM-008', name: 'Scientific Games Monopoly', serialNumber: 'SN-SCI-4401', venue: 'Riverside RSL Club', status: 'archived', description: '', createdBy: 'System seed', lastUpdatedBy: 'System seed' },
  { id: 'm-9', machineId: 'EGM-009', name: 'Everi Fortune Coin 1', serialNumber: 'SN-EVE-5501', venue: 'Riverside RSL Club', status: 'active', description: '', createdBy: 'System seed', lastUpdatedBy: 'System seed' },
  { id: 'm-10', machineId: 'EGM-010', name: 'Everi Fortune Coin 2', serialNumber: 'SN-EVE-5502', venue: 'Riverside RSL Club', status: 'active', description: '', createdBy: 'System seed', lastUpdatedBy: 'System seed' },
  { id: 'm-11', machineId: 'EGM-011', name: 'Aristocrat Buffalo 1', serialNumber: 'SN-AR-00221', venue: 'Riverside RSL Club', status: 'active', description: '', createdBy: 'System seed', lastUpdatedBy: 'System seed' },
  { id: 'm-12', machineId: 'EGM-012', name: 'Aristocrat Buffalo 2', serialNumber: 'SN-AR-00222', venue: 'Riverside RSL Club', status: 'archived', description: '', createdBy: 'System seed', lastUpdatedBy: 'System seed' },

  // Northside Sports Club (8 machines: 5 Active, 3 Archived)
  { id: 'm-13', machineId: 'EGM-013', name: 'Aristocrat Wild Panda 1', serialNumber: 'SN-AR-00331', venue: 'Northside Sports Club', status: 'active', description: '', createdBy: 'System seed', lastUpdatedBy: 'System seed' },
  { id: 'm-14', machineId: 'EGM-014', name: 'Aristocrat Wild Panda 2', serialNumber: 'SN-AR-00332', venue: 'Northside Sports Club', status: 'active', description: '', createdBy: 'System seed', lastUpdatedBy: 'System seed' },
  { id: 'm-15', machineId: 'EGM-015', name: 'IGT Double Diamond 1', serialNumber: 'SN-IGT-3301', venue: 'Northside Sports Club', status: 'archived', description: '', createdBy: 'System seed', lastUpdatedBy: 'System seed' },
  { id: 'm-16', machineId: 'EGM-016', name: 'IGT Double Diamond 2', serialNumber: 'SN-IGT-3302', venue: 'Northside Sports Club', status: 'active', description: '', createdBy: 'System seed', lastUpdatedBy: 'System seed' },
  { id: 'm-17', machineId: 'EGM-017', name: 'Konami China Shores', serialNumber: 'SN-KON-4401', venue: 'Northside Sports Club', status: 'active', description: '', createdBy: 'System seed', lastUpdatedBy: 'System seed' },
  { id: 'm-18', machineId: 'EGM-018', name: 'Scientific Games Zeus', serialNumber: 'SN-SCI-5501', venue: 'Northside Sports Club', status: 'archived', description: '', createdBy: 'System seed', lastUpdatedBy: 'System seed' },
  { id: 'm-19', machineId: 'EGM-019', name: 'Everi Black Diamond', serialNumber: 'SN-EVE-6601', venue: 'Northside Sports Club', status: 'archived', description: '', createdBy: 'System seed', lastUpdatedBy: 'System seed' },
  { id: 'm-20', machineId: 'EGM-020', name: 'Aristocrat Timber Wolf', serialNumber: 'SN-AR-00441', venue: 'Northside Sports Club', status: 'active', description: '', createdBy: 'System seed', lastUpdatedBy: 'System seed' },
];

export const initialBlacklist = [
  { id: 'bl-001', name: 'Marcus Vance', alias: 'Mark Vance', dob: '14/05/1982', reason: 'Self-exclusion order #8841', state: 'NSW', addedDate: '12 Jan 2026', severity: 'High', status: 'Active' },
  { id: 'bl-002', name: 'Elena Rostova', alias: 'Helen Ross', dob: '22/09/1979', reason: 'Anti-money laundering SMR inquiry', state: 'VIC', addedDate: '04 Mar 2026', severity: 'High', status: 'Active' },
  { id: 'bl-003', name: 'David K. Lawson', alias: 'Dave Lawson', dob: '30/11/1990', reason: 'Repeated suspicious transaction structuring', state: 'NSW', addedDate: '19 Apr 2026', severity: 'Medium', status: 'Active' },
  { id: 'bl-004', name: 'Chloe Gallagher', alias: 'C. Gallagher', dob: '08/02/1985', reason: 'Club barring order 12-months', state: 'QLD', addedDate: '01 Jun 2026', severity: 'Low', status: 'Active' },
  { id: 'bl-005', name: 'Tariq Al-Mansoor', alias: 'Terry Mansoor', dob: '17/07/1974', reason: 'Sanctions match cross-reference', state: 'NSW', addedDate: '14 Jul 2026', severity: 'High', status: 'Active' },
];

const payoutStatuses = ['Draft', 'Payment Delayed', 'Payment Completed', 'Pending Authorisation', 'Awaiting Approval', 'Pending verification', 'Failed', 'Rejected'];
const venuesList = ['Riverside RSL Club', 'Riverside Grand Bistro', 'Riverside Lounge & Bar', 'Riverside Leisure Center', 'Riverside Bowling Club'];

export const initialPayouts = [
  // Patron self-service verification in flight: the collector has submitted, the
  // patron has not finished on their phone yet, so ID, screening and CoP are all
  // still empty and no approver can action these.
  { id: '575', created: 'Jul 13, 2026 12:58PM', venue: 'Riverside RSL Club', idv: 'None', pep: '-', sanctions: '-', cop: '-', amount: 8400, status: 'Pending verification', risk: 'Medium', machineId: 'EGM-006', member: 'MEM-1041', accountName: 'Priya Raman', bsb: '-', accountNumber: '-' },
  { id: '574', created: 'Jul 13, 2026 12:22PM', venue: 'Riverside RSL Club', idv: 'None', pep: '-', sanctions: '-', cop: '-', amount: 1250, status: 'Pending verification', risk: 'Low', machineId: 'EGM-011', member: 'MEM-1042', accountName: 'Daniel Okafor', bsb: '-', accountNumber: '-' },
  { id: '573', created: 'Jul 13, 2026 11:58AM', venue: 'Riverside Grand Bistro', idv: 'None', pep: '-', sanctions: '-', cop: '-', amount: 15000, status: 'Pending verification', risk: 'High', machineId: 'EGM-007', member: 'MEM-1043', accountName: 'Helena Vasquez', bsb: '-', accountNumber: '-' },
  { id: '572', created: 'Jul 13, 2026 11:47AM', venue: 'Riverside RSL Club', idv: 'None', pep: '—', sanctions: '—', cop: '—', amount: 6000, status: 'Draft', risk: 'High', machineId: 'EGM-001', member: 'MEM-1001', accountName: 'Sarah Jenkins', bsb: '062-000', accountNumber: '12345678' },
  { id: '570', created: 'Jul 13, 2026 06:31AM', venue: 'Riverside RSL Club', idv: 'Fail', pep: 'Clear', sanctions: 'Clear', cop: 'No match', amount: 400, status: 'Payment Delayed', risk: 'High', machineId: 'EGM-003', member: 'MEM-1002', accountName: 'James O\'Sullivan', bsb: '032-001', accountNumber: '87654321' },
  { id: '569', created: 'Jul 10, 2026 11:10AM', venue: 'Riverside RSL Club', idv: 'Pass', pep: 'Clear', sanctions: 'Clear', cop: 'Match', amount: 999, status: 'Payment Completed', risk: 'Low', machineId: 'EGM-002', member: 'MEM-1003', accountName: 'David Zhang', bsb: '012-002', accountNumber: '45678901' },
  { id: '567', created: 'Jul 09, 2026 12:31PM', venue: 'Riverside Grand Bistro', idv: 'Manual verification', pep: 'Clear', sanctions: 'Clear', cop: 'Close match', amount: 56, status: 'Pending Authorisation', risk: 'Medium', machineId: 'EGM-007', member: 'MEM-1004', accountName: 'Elena Rostova', bsb: '082-004', accountNumber: '99887766' },
  { id: '566', created: 'Jul 09, 2026 10:22AM', venue: 'Riverside Lounge & Bar', idv: 'Manual verification', pep: 'Pending', sanctions: 'Clear', cop: 'Close match', amount: 200, status: 'Awaiting Approval', risk: 'Medium', machineId: 'EGM-005', member: 'MEM-1005', accountName: 'Marcus Vance', bsb: '062-000', accountNumber: '11223344' },
  { id: '565', created: 'Jul 09, 2026 10:10AM', venue: 'Riverside Leisure Center', idv: 'Fail', pep: 'Clear', sanctions: 'Clear', cop: 'No match', amount: 230, status: 'Draft', risk: 'High', machineId: 'EGM-008', member: 'MEM-1006', accountName: 'Chloe Gallagher', bsb: '032-001', accountNumber: '55667788' },
  { id: '564', created: 'Jul 09, 2026 09:24AM', venue: 'Riverside RSL Club', idv: 'None', pep: '—', sanctions: '—', cop: '—', amount: 34, status: 'Draft', risk: 'High', machineId: 'EGM-004', member: 'MEM-1007', accountName: 'Terry Mansoor', bsb: '012-002', accountNumber: '66778899' },
  { id: '563', created: 'Jul 09, 2026 09:13AM', venue: 'Riverside Grand Bistro', idv: 'Fail', pep: 'Hit', sanctions: 'Clear', cop: 'No match', amount: 25000, status: 'Failed', risk: 'High', machineId: 'EGM-001', member: 'MEM-1008', accountName: 'Robert Sterling', bsb: '082-004', accountNumber: '22334455' },
  { id: '562', created: 'Jul 09, 2026 06:57AM', venue: 'Riverside RSL Club', idv: 'Fail', pep: 'Clear', sanctions: 'Hit', cop: 'No match', amount: 25000, status: 'Rejected', risk: 'High', machineId: 'EGM-006', member: 'MEM-1009', accountName: 'Stacy Testtwenty', bsb: '062-000', accountNumber: '33445566' },
  { id: '560', created: 'Jul 08, 2026 12:50PM', venue: 'Riverside Lounge & Bar', idv: 'Manual verification', pep: 'Clear', sanctions: 'Clear', cop: 'Close match', amount: 760, status: 'Awaiting Approval', risk: 'Medium', machineId: 'EGM-002', member: 'MEM-1010', accountName: 'Kevin Patterson', bsb: '032-001', accountNumber: '77889900' },
  { id: '559', created: 'Jul 07, 2026 04:21PM', venue: 'Riverside RSL Club', idv: 'Fail', pep: 'Clear', sanctions: 'Clear', cop: 'Match', amount: 30, status: 'Payment Completed', risk: 'High', machineId: 'EGM-003', member: 'MEM-1011', accountName: 'Hannah Abbott', bsb: '012-002', accountNumber: '88990011' },
  { id: '558', created: 'Jul 07, 2026 04:12PM', venue: 'Riverside Leisure Center', idv: 'Pass', pep: 'Clear', sanctions: 'Clear', cop: 'Match', amount: 6500.05, status: 'Draft', risk: 'Low', machineId: 'EGM-005', member: 'MEM-1012', accountName: 'Liam Cooper', bsb: '082-004', accountNumber: '99001122' },
  { id: '557', created: 'Jul 07, 2026 04:10PM', venue: 'Riverside RSL Club', idv: 'Pass', pep: 'Clear', sanctions: 'Clear', cop: 'Match', amount: 35000, status: 'Draft', risk: 'Low', machineId: 'EGM-001', member: 'MEM-1013', accountName: 'Olivia Taylor', bsb: '062-000', accountNumber: '44556677' },
  { id: '556', created: 'Jul 07, 2026 12:17PM', venue: 'Riverside Grand Bistro', idv: 'Manual verification', pep: 'Clear', sanctions: 'Clear', cop: 'Close match', amount: 5000.99, status: 'Awaiting Approval', risk: 'Medium', machineId: 'EGM-007', member: 'MEM-1014', accountName: 'Benjamin Scott', bsb: '032-001', accountNumber: '55667788' },
  { id: '555', created: 'Jul 07, 2026 10:50AM', venue: 'Riverside RSL Club', idv: 'Fail', pep: 'Clear', sanctions: 'Clear', cop: 'Match', amount: 800, status: 'Payment Completed', risk: 'High', machineId: 'EGM-002', member: 'MEM-1015', accountName: 'Grace Wilson', bsb: '012-002', accountNumber: '66778899' },
  { id: '554', created: 'Jul 07, 2026 07:50AM', venue: 'Riverside Lounge & Bar', idv: 'Fail', pep: 'Hit', sanctions: 'Clear', cop: 'Close match', amount: 25000, status: 'Awaiting Approval', risk: 'High', machineId: 'EGM-004', member: 'MEM-1016', accountName: 'Lucas Martin', bsb: '082-004', accountNumber: '77889900' },
  { id: '553', created: 'Jul 07, 2026 07:06AM', venue: 'Riverside RSL Club', idv: 'Fail', pep: 'Clear', sanctions: 'Hit', cop: 'No match', amount: 25000, status: 'Failed', risk: 'High', machineId: 'EGM-006', member: 'MEM-1017', accountName: 'Mia Anderson', bsb: '062-000', accountNumber: '88990011' },
  { id: '551', created: 'Jul 06, 2026 12:59PM', venue: 'Riverside Leisure Center', idv: 'Manual verification', pep: 'Clear', sanctions: 'Clear', cop: 'Close match', amount: 51.40, status: 'Draft', risk: 'Medium', machineId: 'EGM-008', member: 'MEM-1018', accountName: 'Noah Thomas', bsb: '032-001', accountNumber: '99001122' },
  { id: '550', created: 'Jul 06, 2026 11:20AM', venue: 'Riverside RSL Club', idv: 'Manual verification', pep: 'Clear', sanctions: 'Clear', cop: 'Match', amount: 536, status: 'Payment Completed', risk: 'Medium', machineId: 'EGM-003', member: 'MEM-1019', accountName: 'Sophia Jackson', bsb: '012-002', accountNumber: '11223344' },
  { id: '549', created: 'Jul 06, 2026 10:48AM', venue: 'Riverside Grand Bistro', idv: 'Pass', pep: 'Clear', sanctions: 'Clear', cop: 'Match', amount: 350, status: 'Awaiting Approval', risk: 'Low', machineId: 'EGM-005', member: 'MEM-1020', accountName: 'Alexander White', bsb: '082-004', accountNumber: '22334455' },
  ...Array.from({ length: 76 }, (_, index) => {
    const i = index + 21;
    const isHigh = i % 3 === 0;
    const isMedium = i % 3 === 1;
    const risk = isHigh ? 'High' : isMedium ? 'Medium' : 'Low';
    const amount = isHigh ? (12000 + ((i * 1350) % 23000)) : (1500 + ((i * 680) % 8000));
    const kyc = isHigh ? (i % 2 === 0 ? 'Fail' : 'Manual verification') : isMedium ? 'Manual verification' : 'Pass';
    const pep = isHigh ? (i % 4 === 0 ? 'Hit' : 'Pending') : isMedium ? (i % 2 === 0 ? 'Pending' : 'Clear') : 'Clear';
    const sanctions = isHigh && i % 6 === 0 ? 'Hit' : 'Clear';
    const cop = isHigh ? (i % 2 === 0 ? 'No match' : 'Close match') : isMedium ? 'Close match' : 'Match';
    const venue = venuesList[i % venuesList.length];
    
    return {
      id: String(548 - i),
      venue,
      amount: amount,
      created: `Jul 0${(i % 5) + 1}, 2026 09:${String(10 + (i * 3) % 45).padStart(2, '0')}AM`,
      status: payoutStatuses[i % payoutStatuses.length],
      risk,
      idv: kyc,
      pep,
      sanctions,
      cop,
      machineId: `EGM-${String((i % 8) + 1).padStart(3, '0')}`,
      member: `MEM-${String(1000 + i)}`,
      accountName: i % 4 === 0 ? 'Sarah Jane Jenkins' : 'James O\'Sullivan',
      bsb: '062-000',
      accountNumber: `${10000000 + i * 1111}`,
    };
  })
];

export const initialWinners = [
  {
    id: 'WIN-89201',
    payoutId: 'PAY-260701',
    fullName: 'Stacy Testtwenty',
    memberNumber: 'MEM-3E23E',
    email: 'stacy.testtwenty@gmail.com',
    phone: '+61 412 890 124',
    dob: '14/05/1988',
    address: '42 Macquarie Street, Parramatta NSW 2150',
    venue: 'Riverside RSL Club',
    machineId: 'EGM-002',
    machineName: 'Dragon Link 1',
    winAmount: 1500.00,
    cashDisbursed: 500.00,
    eftDisbursed: 1000.00,
    winTimestamp: '14 Jul 2026, 07:09',
    payoutStatus: 'Awaiting Approval',
    idvStatus: 'Pass',
    idvDocType: 'Australian Passport',
    dvsResult: 'Verified (DVS)',
    pepStatus: 'Hit',
    sanctionsStatus: 'Hit',
    copStatus: 'Match',
    riskRating: 'High',
    bankDetails: {
      accountName: 'STACY K TESTTWENTY',
      bsb: '032-001',
      accountNumber: '213123123',
      bankName: 'Westpac Banking Corporation'
    },
    isBlacklisted: false,
    blacklistDetails: null,
    collector: { name: 'M. Santos', id: 'usr-1a2b3c' }
  },
  {
    id: 'WIN-89202',
    payoutId: 'PAY-260702',
    fullName: 'Alexander Ross',
    memberNumber: 'MEM-9K12M',
    email: 'alex.ross84@outlook.com',
    phone: '+61 423 771 902',
    dob: '29/11/1984',
    address: '18 George Street, Sydney NSW 2000',
    venue: 'Riverside RSL Club',
    machineId: 'EGM-004',
    machineName: 'Buffalo Gold',
    winAmount: 4200.00,
    cashDisbursed: 1200.00,
    eftDisbursed: 3000.00,
    winTimestamp: '14 Jul 2026, 08:15',
    payoutStatus: 'Awaiting Approval',
    idvStatus: 'Pass',
    idvDocType: 'NSW Driver Licence',
    dvsResult: 'Verified (DVS)',
    pepStatus: 'Hit',
    sanctionsStatus: 'Clear',
    copStatus: 'Match',
    riskRating: 'Medium',
    bankDetails: {
      accountName: 'ALEXANDER ROSS',
      bsb: '062-111',
      accountNumber: '445566778',
      bankName: 'Commonwealth Bank of Australia'
    },
    isBlacklisted: false,
    blacklistDetails: null,
    collector: { name: 'M. Santos', id: 'usr-1a2b3c' }
  },
  {
    id: 'WIN-89203',
    payoutId: 'PAY-260703',
    fullName: 'Marcus Vance',
    memberNumber: 'MEM-44021',
    email: 'm.vance@vancetech.com.au',
    phone: '+61 401 229 841',
    dob: '14/05/1982',
    address: '77 Ocean Drive, Manly NSW 2095',
    venue: 'Riverside RSL Club',
    machineId: 'EGM-001',
    machineName: 'Lightning Link 1',
    winAmount: 18500.00,
    cashDisbursed: 0.00,
    eftDisbursed: 18500.00,
    winTimestamp: '13 Jul 2026, 21:40',
    payoutStatus: 'Failed',
    idvStatus: 'Pass',
    idvDocType: 'NSW Driver Licence',
    dvsResult: 'Verified (DVS)',
    pepStatus: 'Clear',
    sanctionsStatus: 'Clear',
    copStatus: 'Match',
    riskRating: 'High',
    bankDetails: {
      accountName: 'MARCUS VANCE',
      bsb: '082-001',
      accountNumber: '998811223',
      bankName: 'National Australia Bank'
    },
    isBlacklisted: true,
    blacklistDetails: {
      id: 'bl-001',
      reason: 'Self-exclusion order #8841',
      severity: 'High',
      state: 'NSW',
      addedDate: '12 Jan 2026'
    },
    collector: { name: 'J. Chen', id: 'usr-2b3c4d' }
  },
  {
    id: 'WIN-89204',
    payoutId: 'PAY-260704',
    fullName: 'Sarah Jane Jenkins',
    memberNumber: 'MEM-10884',
    email: 'sarah.jenkins@gmail.com',
    phone: '+61 433 991 204',
    dob: '03/08/1991',
    address: '120 Victoria Road, Gladesville NSW 2111',
    venue: 'Riverside RSL Club',
    machineId: 'EGM-003',
    machineName: 'Wheel of Fortune',
    winAmount: 6750.00,
    cashDisbursed: 500.00,
    eftDisbursed: 6250.00,
    winTimestamp: '13 Jul 2026, 19:12',
    payoutStatus: 'Payment Completed',
    idvStatus: 'Pass',
    idvDocType: 'Australian Passport',
    dvsResult: 'Verified (DVS)',
    pepStatus: 'Clear',
    sanctionsStatus: 'Clear',
    copStatus: 'Match',
    riskRating: 'Low',
    bankDetails: {
      accountName: 'SARAH JANE JENKINS',
      bsb: '012-003',
      accountNumber: '554433221',
      bankName: 'ANZ Banking Group'
    },
    isBlacklisted: false,
    blacklistDetails: null,
    collector: { name: 'M. Santos', id: 'usr-1a2b3c' }
  },
  {
    id: 'WIN-89205',
    payoutId: 'PAY-260705',
    fullName: 'James O\'Sullivan',
    memberNumber: 'MEM-22910',
    email: 'josullivan@sullivanlaw.com.au',
    phone: '+61 405 667 891',
    dob: '17/12/1976',
    address: '55 Pitt Street, Sydney NSW 2000',
    venue: 'Riverside Bowling Club',
    machineId: 'EGM-007',
    machineName: 'Dollar Storm',
    winAmount: 9800.00,
    cashDisbursed: 0.00,
    eftDisbursed: 9800.00,
    winTimestamp: '12 Jul 2026, 16:30',
    payoutStatus: 'Payment Completed',
    idvStatus: 'Pass',
    idvDocType: 'NSW Driver Licence',
    dvsResult: 'Verified (DVS)',
    pepStatus: 'Clear',
    sanctionsStatus: 'Clear',
    copStatus: 'Match',
    riskRating: 'Low',
    bankDetails: {
      accountName: 'JAMES O\'SULLIVAN',
      bsb: '032-001',
      accountNumber: '112233445',
      bankName: 'Westpac Banking Corporation'
    },
    isBlacklisted: false,
    blacklistDetails: null,
    collector: { name: 'J. Chen', id: 'usr-2b3c4d' }
  },
  {
    id: 'WIN-89206',
    payoutId: 'PAY-260706',
    fullName: 'Elena Rostova',
    memberNumber: 'MEM-33109',
    email: 'elena.rostova@consulting.com',
    phone: '+61 418 234 901',
    dob: '22/09/1979',
    address: '88 Collins Street, Melbourne VIC 3000',
    venue: 'Northside Leagues Club',
    machineId: 'EGM-013',
    machineName: 'Aristocrat Wild Panda 1',
    winAmount: 24500.00,
    cashDisbursed: 500.00,
    eftDisbursed: 24000.00,
    winTimestamp: '12 Jul 2026, 14:05',
    payoutStatus: 'Failed',
    idvStatus: 'Manual verification',
    idvDocType: 'International Passport',
    dvsResult: 'Manual Visual Attestation',
    pepStatus: 'Hit',
    sanctionsStatus: 'Hit',
    copStatus: 'No match',
    riskRating: 'High',
    bankDetails: {
      accountName: 'HELEN ROSS',
      bsb: '063-000',
      accountNumber: '776655443',
      bankName: 'Commonwealth Bank of Australia'
    },
    isBlacklisted: true,
    blacklistDetails: {
      id: 'bl-002',
      reason: 'Anti-money laundering SMR inquiry',
      severity: 'High',
      state: 'VIC',
      addedDate: '04 Mar 2026'
    },
    collector: { name: 'P. Sharma', id: 'usr-6f7g8h' }
  },
  {
    id: 'WIN-89207',
    payoutId: 'PAY-260707',
    fullName: 'David K. Lawson',
    memberNumber: 'MEM-55120',
    email: 'd.lawson@construction.com.au',
    phone: '+61 411 902 334',
    dob: '30/11/1990',
    address: '14 Bayview Crescent, Cronulla NSW 2230',
    venue: 'Northside Leagues Club',
    machineId: 'EGM-015',
    machineName: 'IGT Double Diamond 1',
    winAmount: 11200.00,
    cashDisbursed: 500.00,
    eftDisbursed: 10700.00,
    winTimestamp: '11 Jul 2026, 22:15',
    payoutStatus: 'Pending Authorisation',
    idvStatus: 'Pass',
    idvDocType: 'NSW Driver Licence',
    dvsResult: 'Verified (DVS)',
    pepStatus: 'Clear',
    sanctionsStatus: 'Clear',
    copStatus: 'Close match',
    riskRating: 'Medium',
    bankDetails: {
      accountName: 'DAVID LAWSON',
      bsb: '082-001',
      accountNumber: '665544332',
      bankName: 'National Australia Bank'
    },
    isBlacklisted: true,
    blacklistDetails: {
      id: 'bl-003',
      reason: 'Repeated suspicious transaction structuring',
      severity: 'Medium',
      state: 'NSW',
      addedDate: '19 Apr 2026'
    },
    collector: { name: 'P. Sharma', id: 'usr-6f7g8h' }
  },
  {
    id: 'WIN-89208',
    payoutId: 'PAY-260708',
    fullName: 'Chloe Gallagher',
    memberNumber: 'MEM-66190',
    email: 'chloe.g@outlook.com.au',
    phone: '+61 422 881 772',
    dob: '08/02/1985',
    address: '9 Gold Coast Highway, Surfers Paradise QLD 4217',
    venue: 'Harbourview Hotel',
    machineId: 'EGM-008',
    machineName: 'Cash Express',
    winAmount: 5400.00,
    cashDisbursed: 400.00,
    eftDisbursed: 5000.00,
    winTimestamp: '10 Jul 2026, 18:45',
    payoutStatus: 'Payment Completed',
    idvStatus: 'Pass',
    idvDocType: 'QLD Driver Licence',
    dvsResult: 'Verified (DVS)',
    pepStatus: 'Clear',
    sanctionsStatus: 'Clear',
    copStatus: 'Match',
    riskRating: 'Low',
    bankDetails: {
      accountName: 'CHLOE GALLAGHER',
      bsb: '014-002',
      accountNumber: '990011223',
      bankName: 'ANZ Banking Group'
    },
    isBlacklisted: true,
    blacklistDetails: {
      id: 'bl-004',
      reason: 'Club barring order 12-months',
      severity: 'Low',
      state: 'QLD',
      addedDate: '01 Jun 2026'
    },
    collector: { name: 'P. Sharma', id: 'usr-6f7g8h' }
  },
  {
    id: 'WIN-89209',
    payoutId: 'PAY-260709',
    fullName: 'Tariq Al-Mansoor',
    memberNumber: 'MEM-77182',
    email: 'tariq.mansoor@trade.com.au',
    phone: '+61 409 112 345',
    dob: '17/07/1974',
    address: '202 Elizabeth Street, Sydney NSW 2000',
    venue: 'Harbourview Hotel',
    machineId: 'EGM-005',
    machineName: 'Grand Star',
    winAmount: 19800.00,
    cashDisbursed: 500.00,
    eftDisbursed: 19300.00,
    winTimestamp: '09 Jul 2026, 20:10',
    payoutStatus: 'Failed',
    idvStatus: 'Manual verification',
    idvDocType: 'Foreign Passport + Utility Bill',
    dvsResult: 'Manual Visual Attestation',
    pepStatus: 'Hit',
    sanctionsStatus: 'Hit',
    copStatus: 'No match',
    riskRating: 'High',
    bankDetails: {
      accountName: 'TERRY MANSOOR',
      bsb: '032-005',
      accountNumber: '334455667',
      bankName: 'Westpac Banking Corporation'
    },
    isBlacklisted: true,
    blacklistDetails: {
      id: 'bl-005',
      reason: 'Sanctions match cross-reference',
      severity: 'High',
      state: 'NSW',
      addedDate: '14 Jul 2026'
    },
    collector: { name: 'P. Sharma', id: 'usr-6f7g8h' }
  },
  {
    id: 'WIN-89210',
    payoutId: 'PAY-260710',
    fullName: 'Liam Patrick Murphy',
    memberNumber: 'MEM-88291',
    email: 'liam.murphy@sydneyrail.nsw.gov.au',
    phone: '+61 414 556 778',
    dob: '25/03/1983',
    address: '33 Church Street, Parramatta NSW 2150',
    venue: 'Riverside RSL Club',
    machineId: 'EGM-006',
    machineName: 'Lock It Link',
    winAmount: 7600.00,
    cashDisbursed: 500.00,
    eftDisbursed: 7100.00,
    winTimestamp: '09 Jul 2026, 15:20',
    payoutStatus: 'Payment Completed',
    idvStatus: 'Pass',
    idvDocType: 'NSW Driver Licence',
    dvsResult: 'Verified (DVS)',
    pepStatus: 'Clear',
    sanctionsStatus: 'Clear',
    copStatus: 'Match',
    riskRating: 'Low',
    bankDetails: {
      accountName: 'LIAM P MURPHY',
      bsb: '062-211',
      accountNumber: '887766554',
      bankName: 'Commonwealth Bank of Australia'
    },
    isBlacklisted: false,
    blacklistDetails: null,
    collector: { name: 'M. Santos', id: 'usr-1a2b3c' }
  },
  {
    id: 'WIN-89211',
    payoutId: 'PAY-260711',
    fullName: 'Zoe Annabelle Chen',
    memberNumber: 'MEM-99102',
    email: 'zoechen92@gmail.com',
    phone: '+61 426 339 102',
    dob: '11/10/1992',
    address: '5/18 Railway Parade, Burwood NSW 2134',
    venue: 'Riverside RSL Club',
    machineId: 'EGM-011',
    machineName: 'Aristocrat Buffalo 1',
    winAmount: 3450.00,
    cashDisbursed: 450.00,
    eftDisbursed: 3000.00,
    winTimestamp: '08 Jul 2026, 12:40',
    payoutStatus: 'Payment Completed',
    idvStatus: 'Pass',
    idvDocType: 'Australian Passport',
    dvsResult: 'Verified (DVS)',
    pepStatus: 'Clear',
    sanctionsStatus: 'Clear',
    copStatus: 'Match',
    riskRating: 'Low',
    bankDetails: {
      accountName: 'ZOE A CHEN',
      bsb: '032-024',
      accountNumber: '443322119',
      bankName: 'Westpac Banking Corporation'
    },
    isBlacklisted: false,
    blacklistDetails: null,
    collector: { name: 'M. Santos', id: 'usr-1a2b3c' }
  },
  {
    id: 'WIN-89212',
    payoutId: 'PAY-260712',
    fullName: 'Robert Harrison',
    memberNumber: 'MEM-11928',
    email: 'rob.harrison@transport.com.au',
    phone: '+61 402 778 991',
    dob: '05/06/1971',
    address: '109 Victoria Street, Potts Point NSW 2011',
    venue: 'Riverside Bowling Club',
    machineId: 'EGM-008',
    machineName: 'Cash Express',
    winAmount: 14200.00,
    cashDisbursed: 500.00,
    eftDisbursed: 13700.00,
    winTimestamp: '07 Jul 2026, 19:55',
    payoutStatus: 'Pending Authorisation',
    idvStatus: 'Manual verification',
    idvDocType: 'NSW Driver Licence + Medicare Card',
    dvsResult: 'Manual Visual Attestation',
    pepStatus: 'Clear',
    sanctionsStatus: 'Clear',
    copStatus: 'Close match',
    riskRating: 'Medium',
    bankDetails: {
      accountName: 'ROBERT R HARRISON',
      bsb: '082-901',
      accountNumber: '120934875',
      bankName: 'National Australia Bank'
    },
    isBlacklisted: false,
    blacklistDetails: null,
    collector: { name: 'J. Chen', id: 'usr-2b3c4d' }
  }
];
